server {
  listen 80;
  root /usr/share/nginx/html;
  location / { try_files $uri /index.html; }
  location /customers { proxy_pass http://customer-service:9091; }
  location /restaurants { proxy_pass http://restaurant-service:9092; }
  location /orders { proxy_pass http://order-service:9093; }
  location /payments { proxy_pass http://payment-service:9094; }
  location /deliveries { proxy_pass http://delivery-service:9095; }
  location /notifications { proxy_pass http://notification-service:9096; }
  location /admin { proxy_pass http://admin-service:9097; }
}
